# Generated by Django 5.1.2 on 2024-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video', models.FileField(upload_to='videos/original/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='videos/processed/')),
            ],
        ),
    ]
